spring:
  # ??????
  output:
    ansi:
      enabled: always
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/citydb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource

    # ?? druid ???
    druid:
      # ???????
      max-active: 1000
      # ????????
      initial-size: 10
      # ???????????
      max-wait: 1000
      # ??????
      min-idle: 10
      # ???????? min-evictable-idle-time-millis ?????
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # ????????
      validation-query: select 1
      # ???? validation-query true??? false????
      test-while-idle: true
      # ??????????????????????false?
      test-on-borrow: false
      # ?????????????????????false?
      test-on-return: false
      # ???? preparedStatements (MySql????????????????false)
      pool-prepared-statements: false


    # ?? hikari ????springboot?????????
#    hikari:
#      # ??????
#      minimum-idle: 5
#      # ?????
#      maximum-pool-size: 20
#      # ??????
#      idle-timeout: 900000
#      # ??????
##      connection-timeout: 3
#      # ????????
#      connection-test-query: select 1


