spring:
  datasource:
    c3p0:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/citydb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      user: root
      password: admin123
      min-pool-size: 5
      initial-pool-size: 5
      max-pool-size: 20
      max-idle-time: 2000
      checkout-time-out: 3000
