spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/citydb?serverTimezone=Asia/Shanghai&useUnicode=true&Character
    username: root
    password: admin123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 90000000
#      connection-timeout: 3
      connection-test-query: select 1

mybatis:
  type-aliases-package: com.ming.city.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: MySQL
  reasonable: true
  support-methods-arguments: true
